# Generated by Django 4.1.2 on 2022-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupe',
            name='numberOfStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupe',
            name='numberOfTeachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='familyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
