# Generated by Django 4.1.2 on 2022-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_groupe_name_groupe_numberofstudents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='goupe',
            field=models.IntegerField(null=True),
        ),
    ]
