# Generated by Django 4.1.2 on 2022-10-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0003_student_goupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='goupe',
        ),
    ]
