# Generated by Django 4.1.2 on 2022-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0004_remove_student_goupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('familyName', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
