# Generated by Django 4.1.2 on 2022-10-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='numberOfStudents',
            field=models.IntegerField(db_column='numberOfStudents', default=0),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='numberOfTeachers',
            field=models.IntegerField(db_column='numberOfTeachers', default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='birthday', verbose_name=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_column='email', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='familyName',
            field=models.CharField(db_column='familyName', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(db_column='email', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='familyName',
            field=models.CharField(db_column='familyName', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=100),
        ),
    ]
