# Generated by Django 4.1.2 on 2022-10-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0007_alter_groupe_numberofstudents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupe',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.groupe'),
        ),
    ]
