# Generated by Django 4.1.2 on 2022-10-28 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0008_student_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='street', default='', max_length=100)),
                ('city', models.CharField(db_column='city', default='', max_length=100)),
                ('country', models.CharField(db_column='country', default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=100)),
                ('coef', models.IntegerField(db_column='coefficient', default=0)),
                ('nbHours', models.IntegerField(db_column='number Of Hours', default=0)),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='level',
            field=models.CharField(db_column='level', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='birthday', verbose_name=datetime.date(2022, 10, 28)),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.groupe')),
                ('module', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='groupe',
            field=models.ManyToManyField(to='university_app.groupe'),
        ),
        migrations.AddField(
            model_name='student',
            name='adress',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.adress'),
        ),
    ]
