# Generated by Django 4.1.2 on 2022-11-02 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0009_adress_module_groupe_level_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeTeacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='List_Of_Absence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date', verbose_name=datetime.date(2022, 11, 2))),
                ('motif', models.CharField(db_column='motif', default='', max_length=100)),
                ('justification', models.CharField(db_column='justification', default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleGroupe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSession',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleTeacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='start date', verbose_name=datetime.date(2022, 11, 2))),
                ('end_date', models.DateField(db_column='end date', verbose_name=datetime.date(2022, 11, 2))),
                ('classroom_number', models.IntegerField(db_column='classroom number')),
                ('goal', models.CharField(db_column='goal', default='', max_length=1000)),
                ('summary', models.CharField(db_column='summary', default='', max_length=1000)),
                ('liste_of_tools', models.CharField(choices=[('software tools', 'software tools'), ('hardware tools', 'hardware tools')], db_column='liste of tools', default='', max_length=100)),
                ('state', models.CharField(choices=[('running', 'running'), ('achieved', 'achieved'), ('cancelled', 'cancelled'), ('delayed', 'delayed')], db_column='state', default='', max_length=100)),
                ('type', models.CharField(choices=[('normal', 'normal'), ('catch-up', 'catch-up'), ('support', 'support'), ('training', 'training')], db_column='type', default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='study',
            name='module',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='numberOfTeachers',
        ),
        migrations.RemoveField(
            model_name='module',
            name='coef',
        ),
        migrations.RemoveField(
            model_name='module',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='groupe',
            name='email',
            field=models.EmailField(db_column='email', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='study_level',
            field=models.CharField(db_column='study level', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('optional', 'optional'), ('required', 'required')], db_column='type', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(db_column='photo', default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='situation',
            field=models.CharField(choices=[('new', 'new'), ('repeating', 'repeating'), ('derogatory', 'derogatory'), ('other', 'other')], db_column='situation', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('delayed', 'delayed'), ('excluded', 'excluded')], db_column='state', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='personel_email',
            field=models.EmailField(db_column='personel email', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(db_column='photo', default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_hours_per_week',
            field=models.IntegerField(db_column='total hours per week', default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_email',
            field=models.EmailField(db_column='work email', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='birthday', verbose_name=datetime.date(2022, 11, 2)),
        ),
        migrations.AlterField(
            model_name='student',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='university_app.groupe'),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.AddField(
            model_name='session',
            name='module',
            field=models.ForeignKey(db_column='module', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.module'),
        ),
        migrations.AddField(
            model_name='moduleteacher',
            name='module',
            field=models.ForeignKey(db_column='module', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.module'),
        ),
        migrations.AddField(
            model_name='moduleteacher',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.teacher'),
        ),
        migrations.AddField(
            model_name='modulesession',
            name='module',
            field=models.ForeignKey(db_column='module', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.module'),
        ),
        migrations.AddField(
            model_name='modulesession',
            name='session',
            field=models.ForeignKey(db_column='session', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.session'),
        ),
        migrations.AddField(
            model_name='modulegroupe',
            name='group',
            field=models.ForeignKey(db_column='group', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.groupe'),
        ),
        migrations.AddField(
            model_name='modulegroupe',
            name='module',
            field=models.ForeignKey(db_column='module', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.module'),
        ),
        migrations.AddField(
            model_name='list_of_absence',
            name='student',
            field=models.ForeignKey(db_column='student', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.student'),
        ),
        migrations.AddField(
            model_name='groupeteacher',
            name='group',
            field=models.ForeignKey(db_column='group', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.groupe'),
        ),
        migrations.AddField(
            model_name='groupeteacher',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.teacher'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='module',
            field=models.ManyToManyField(related_name='groups', through='university_app.ModuleGroupe', to='university_app.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='sessions',
            field=models.ManyToManyField(related_name='modules', through='university_app.ModuleSession', to='university_app.session'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groupe',
            field=models.ManyToManyField(related_name='teachers', through='university_app.GroupeTeacher', to='university_app.groupe'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='modules',
            field=models.ManyToManyField(related_name='teachers', through='university_app.ModuleTeacher', to='university_app.module'),
        ),
    ]
