# Generated by Django 4.1.2 on 2022-11-03 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0010_groupeteacher_list_of_absence_modulegroupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_absence',
            name='date',
            field=models.DateField(db_column='date', verbose_name=datetime.date(2022, 11, 3)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(db_column='end date', verbose_name=datetime.date(2022, 11, 3)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(db_column='start date', verbose_name=datetime.date(2022, 11, 3)),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='birthday', verbose_name=datetime.date(2022, 11, 3)),
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='number', default=0)),
                ('street', models.CharField(db_column='street', default='', max_length=100)),
                ('city', models.CharField(db_column='city', default='', max_length=100)),
                ('postal_code', models.IntegerField(db_column='postal code', default=0, max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to='university_app.student')),
            ],
        ),
    ]
