# Generated by Django 4.1.2 on 2022-11-03 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0011_alter_list_of_absence_date_alter_session_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfAbsence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date', verbose_name=django.utils.timezone.now)),
                ('motif', models.CharField(db_column='motif', default='<empty>', max_length=100)),
                ('justification', models.CharField(db_column='justification', default='<empty>', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(db_column='birthday', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.IntegerField(db_column='grade', default=0),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(db_column='city', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.IntegerField(db_column='postal code', default=0),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(db_column='street', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='email',
            field=models.EmailField(db_column='email', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='level',
            field=models.CharField(db_column='level', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='name',
            field=models.CharField(db_column='name', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(db_column='name', default='<empty>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='study_level',
            field=models.CharField(db_column='study level', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('optional', 'optional'), ('required', 'required')], db_column='type', default='optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(db_column='end date', verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='goal',
            field=models.CharField(db_column='goal', default='<empty>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='liste_of_tools',
            field=models.CharField(choices=[('software tools', 'software tools'), ('hardware tools', 'hardware tools')], db_column='liste of tools', default='software tools', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(db_column='start date', verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('running', 'running'), ('achieved', 'achieved'), ('cancelled', 'cancelled'), ('delayed', 'delayed')], db_column='state', default='running', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.CharField(db_column='summary', default='<empty>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('catch-up', 'catch-up'), ('support', 'support'), ('training', 'training')], db_column='type', default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='birthday', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='familyName',
            field=models.CharField(db_column='family Name', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_column='name', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(db_column='photo', default='<empty>', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(choices=[('new', 'new'), ('repeating', 'repeating'), ('derogatory', 'derogatory'), ('other', 'other')], db_column='situation', default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('delayed', 'delayed'), ('excluded', 'excluded')], db_column='state', default='present', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='familyName',
            field=models.CharField(db_column='family Name', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_column='name', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personel_email',
            field=models.EmailField(db_column='personel email', default='<empty>', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(db_column='photo', default='<empty>', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_email',
            field=models.EmailField(db_column='work email', default='<empty>', max_length=100),
        ),
        migrations.DeleteModel(
            name='List_Of_Absence',
        ),
        migrations.AddField(
            model_name='listofabsence',
            name='student',
            field=models.ForeignKey(db_column='student', default=0, on_delete=django.db.models.deletion.CASCADE, to='university_app.student'),
        ),
    ]
