# Generated by Django 4.1.2 on 2022-11-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0012_listofabsence_teacher_birthday_teacher_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adress',
            table='adress',
        ),
        migrations.AlterModelTable(
            name='groupe',
            table='groupe',
        ),
        migrations.AlterModelTable(
            name='groupeteacher',
            table='group teacher association',
        ),
        migrations.AlterModelTable(
            name='listofabsence',
            table='list of absence',
        ),
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
        migrations.AlterModelTable(
            name='modulegroupe',
            table='module group association',
        ),
        migrations.AlterModelTable(
            name='modulesession',
            table='module session association',
        ),
        migrations.AlterModelTable(
            name='moduleteacher',
            table='module teacher association',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
