# Generated by Django 4.1.2 on 2022-11-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0013_alter_adress_table_alter_groupe_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
