# Generated by Django 4.1.2 on 2022-11-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0014_rename_adress_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
